BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'clear'
        font_size: 30
        on_press: app.clear_text()
    TextInput:
        id: input_name
        font_size: 30
        text: ""
    Button:
        text: 'greet'
        font_size: 30
        on_press: app.handle_greet()
    Label:
        text: "Enter your name"
        font_size: 30
        color: (1, 1, 0,1)
        id: output_label